---
- hosts: all  # Replace "all" with your target group
  become: true  # Requires root privileges

  tasks:
    - name: Uninstall Python3 package
      yum:
        name: python3
        state: absent
    - name: Uninstall pip for Python3
      yum:
        name: python3-pip
        state: absent
