---
- hosts: all  # Replace "all" with your target group if needed
  become: true  # Requires root privileges

  tasks:
    - name: Install Nginx package
      yum:
        name: nginx
        state: present
      # Optional: Enable and start the service after installation
    - name: Enable and start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
