#This script used for installing Docker, Helm, K3s

---

- hosts: dev
  become: true
  tasks:
   - name: Install packages that allow apt to be used over HTTPS
     apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
     vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

   - name: Add an apt signing key for Docker
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add apt repository for stable version
     apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

   - name: Install docker and its dependecies
     apt:
       name: "{{ packages }}"
       state: present
       update_cache: yes
     vars:
       packages:
       - docker-ce
       - docker-ce-cli
       - containerd.io

   - name: Update apt package manager repositories cache
     become: true
     apt:
       update_cache: yes

   - name: Bacically apt-get update
     apt:
        update_cache: yes

   - name: Download helm
     get_url:
       url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
       dest: /root
       mode: u+x

   - name: Install Helm
     shell: bash /root/get-helm-3
     become: yes

   - name: Bacically apt-get update
     apt:
      update_cache: yes

   - name: Download k3s binary x64
     get_url:
      url: https://get.k3s.io
      dest: /usr/local/bin/
      mode: u+x

   - name: Install k3s
     shell: bash /usr/local/bin/index.html

   - name: Update K3s permission
     become: true
     shell: sudo chmod 666 /etc/rancher/k3s/k3s.yaml
     args:
       chdir: /home/core

   - name: Update docker permission
     become: true
     shell: sudo chmod 666 /var/run/docker.sock
     args:
       chdir: /home/core
       warn: false
   - name: Create an empty .bash_profile file
     file:
       path: "/home/core/.bash_profile"
       state: touch
   - name: Add a env variable for helm
     copy:
       dest: "/home/core/.bash_profile"
       content: |
         export KUBECONFIG=/etc/rancher/k3s/k3s.yaml  
